name: smartsearch
description: Application mobile de recherche multimodale (texte et image) connectée à une plateforme e-commerce

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.1.1

  # Network & API
  http: ^1.1.0
  dio: ^5.4.0

  # Authentication
  flutter_secure_storage: ^9.0.0
  jwt_decoder: ^2.0.1

  # Image Handling
  image_picker: ^1.0.7
  cached_network_image: ^3.3.1

  # UI Components
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9
  shimmer: ^3.0.0

  # Utils
  intl: ^0.19.0
  equatable: ^2.0.5
  shared_preferences: ^2.2.2
  share_plus: ^10.0.0
  url_launcher: ^6.3.0
  package_info_plus: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.8


flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: assets/fonts/Roboto-Regular.ttf
  #       - asset: assets/fonts/Roboto-Bold.ttf
  #         weight: 700
